### ISSUE TITLE
colors don't parse properly

### ISSUE THREAD

**Issue by lolpro11** [0xCUB3/nofetch#1]
`\033[38;5;1mOS: AmogOS
\033[38;5;1mHost: Grandma's Computer
\033[38;5;1mUptime: 69 years, 420 days
\033[38;5;1mCPU: AMD Ryzen Threadripper 6990X (420) @ 6.90Ghz
\033[38;5;1mGPU: NVIDIA RTX 6090 1024 GB
\033[38;5;1mMemory: 0.0000001MiB / 4300800MiB
`

**Comment by 0xCUB3** [comment]
Please input your OS, kernel version, and if possible, what packages you have installed.

**Comment by lolpro11** [comment]
OS: AmogOS
Host: Grandma's Computer
Uptime: 69 years, 420 days
CPU: AMD Ryzen Threadripper 6990X (420) @ 6.90Ghz 
GPU: NVIDIA RTX 6090 1024 GB
Memory: 0.0000001MiB / 4300800MiB

**Comment by 0xCUB3** [comment]
bruh. I mean your real OS lol

**Comment by lolpro11** [comment]
> bruh. I mean your real OS lol

Arch btw

**Comment by 0xCUB3** [comment]
Closing this as I'm assuming you're trolling. Feel free to open a new thread with more sufficient information if you wish.

**Comment by lolpro11** [comment]
> Closing this as I'm assuming you're trolling. Feel free to open a new thread with more sufficient information if you wish.

                   -`                    lolpro11@wife 
                  .o+`                   ------------- 
                 `ooo/                   OS: Arch Linux x86_64 
                `+oooo:                  Host: HP EliteBook Folio 9470m A1029D1102 
               `+oooooo:                 Kernel: 5.15.11-arch2-1 
               -+oooooo+:                Uptime: 2 days, 21 hours, 10 mins 
             `/:-:++oooo+:               Packages: 1289 (pacman) 
            `/++++/+++++++:              Shell: bash 5.1.12 
           `/++++++++++++++:             Resolution: 1600x900 
          `/+++ooooooooooooo/`           DE: Plasma 5.23.4 
         ./ooosssso++osssssso+`          WM: KWin 
        .oossssso-````/ossssss+`         Theme: Breeze Light [Plasma], Breeze [GTK2/3] 
       -osssssso.      :ssssssso.        Icons: [Plasma], breeze-dark [GTK2/3] 
      :osssssss/        osssso+++.       Terminal: konsole 
     /ossssssss/        +ssssooo/-       CPU: Intel i5-3437U (4) @ 2.900GHz 
   `/ossssso+/:-        -:/+osssso+-     GPU: Intel 3rd Gen Core processor Graphics Controller 
  `+sso+:-`                 `.-/+oso:    Memory: 6346MiB / 7813MiB 
 `++:.                           `-/+/
 .`                                 `/
