### ISSUE TITLE
colors dont parse properly

### ISSUE THREAD

**Issue by lolpro11** [0xCUB3/nofetch#2]
Kernel: 5.15.11-arch2-1
OS: Arch Linux x86_64

**Comment by 0xCUB3** [comment]
please elaborate on the issue

**Comment by lolpro11** [comment]
Raw output:

\033[38;5;1mOS: AmogOS
\033[38;5;1mHost: Grandma's Computer
\033[38;5;1mUptime: 69 years, 420 days
\033[38;5;1mCPU: AMD Ryzen Threadripper 6990X (420) @ 6.90Ghz
\033[38;5;1mGPU: NVIDIA RTX 6090 1024 GB
\033[38;5;1mMemory: 0.0000001MiB / 4300800MiB

**Comment by 0xCUB3** [comment]
I'll look into the problem/

**Comment by 0xCUB3** [comment]
@lolpro11 Please try the latest commit (not release) of the repo. Your problem should be solved, thanks to @demodulatingswan
