### ISSUE TITLE
color leaking

### ISSUE THREAD

**Issue by sctech-tr** [0xCUB3/nofetch#7]
see
https://sctech.mooo.com/img/shared/nofetch1.png
https://sctech.mooo.com/img/shared/nofetch2.png
https://sctech.mooo.com/img/shared/nofetch3.png

the colors are leaking to your username

**Comment by 0xCUB3** [comment]
I don't see any leaking. Could this be an issue in your display?

**Comment by sctech-tr** [comment]
maybe. i don't think this is an issue after all

**Comment by cD1rtX3** [comment]
I think this is fixed by #11, actually!
